services:
  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "mdasifshamim/configserver:v1"
    container_name: configserver-ms
    ports:
      - "9992:9992"
    healthcheck:
      test: "curl --fail --silent localhost:9992/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  studentmicroserviceengine:
    image: "mdasifshamim/studentmicrosrviceengine:v1"
    container_name: student-ms
    ports:
      - "9991:9991"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "students"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  educationautomateengine:
    driver: "bridge"

